# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0594ef1075d7de840e4d363eb57a305b2082d7fefe75383f95eee4807af28e79abdf9dddd2426710273d0da28da5ffde8c86d161ce4cca6db45d9f56055a5d0

test:
  secret_key_base: 54c2911a38272d608205d74746a82e1f4b8b15733546f3d40b66cdc30f77a44c1e49accc4588323b3c87ebc4e5eb4b66c9009d7f4408fc29c8d40a8408c38332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
